# Generated by Axiom CLI — do not delete.
# Ensures pytest can resolve "from nodes.<module> import <func>" imports
# whether tests are run from the package root or inside the Docker build.
import sys, os as _os
sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))

import io as _io

import numpy as _np
import pytest
from PIL import Image as _PILImage
from gen.messages_pb2 import Image as _Image


def _png_bytes(arr: "_np.ndarray") -> bytes:
    """Encode a uint8 numpy array (2D gray or HxWx3 RGB) as PNG bytes."""
    mode = "L" if arr.ndim == 2 else "RGB"
    buf = _io.BytesIO()
    _PILImage.fromarray(arr.astype("uint8"), mode=mode).save(buf, format="PNG")
    return buf.getvalue()


def _image_msg(arr: "_np.ndarray") -> "_Image":
    return _Image(data=_png_bytes(arr), format="PNG")


class _TestContext:
    """Minimal AxiomContext double shared by every node test in this package."""

    class _Logger:
        def debug(self, msg: str, **attrs) -> None: pass
        def info(self, msg: str, **attrs) -> None: pass
        def warn(self, msg: str, **attrs) -> None: pass
        def error(self, msg: str, **attrs) -> None: pass

    class _Secrets:
        def get(self, name: str):
            return ("", False)

        def status(self, name: str):
            from gen.axiom_context import SecretStatus
            return SecretStatus.UNSET

    def __init__(self) -> None:
        self.log = self._Logger()
        self.secrets = self._Secrets()
        self.execution_id = "test-execution-id"
        self.flow_id = "test-flow-id"
        self.tenant_id = "test-tenant-id"


@pytest.fixture
def ax():
    return _TestContext()


@pytest.fixture
def png_bytes():
    return _png_bytes


@pytest.fixture
def image_msg():
    return _image_msg


# ---------------------------------------------------------------------------
# Synthetic oracle fixtures: known-ground-truth images. Areas/centroids/
# perimeters below are HAND-COMPUTED from the exact rectangle coordinates
# used to build the array — independent of scikit-image's own measurement
# code, so they serve as a real correctness oracle for RegionProps/
# CountObjects/Threshold/Morphology/FindContours.

@pytest.fixture
def three_squares():
    """A 100x120 black canvas with three non-touching white axis-aligned
    squares/rectangles of exactly known size, position, area, and centroid.
    Connectivity-safe: every square is separated from the others by >= 10
    background pixels on all sides.
    """
    h, w = 100, 120
    arr = _np.zeros((h, w), dtype=_np.uint8)
    # (row0, col0, row1, col1) -- half-open [row0:row1, col0:col1]
    boxes = [
        (5, 5, 15, 15),      # 10x10 = 100 px, center (9.5, 9.5)
        (30, 30, 70, 90),    # 40x60 = 2400 px, center (49.5, 59.5)
        (80, 100, 96, 116),  # 16x16 = 256 px, center (87.5, 107.5)
    ]
    for r0, c0, r1, c1 in boxes:
        arr[r0:r1, c0:c1] = 255
    areas = [(r1 - r0) * (c1 - c0) for r0, c0, r1, c1 in boxes]
    centroids = [((r0 + r1 - 1) / 2.0, (c0 + c1 - 1) / 2.0) for r0, c0, r1, c1 in boxes]
    return {"arr": arr, "boxes": boxes, "areas": areas, "centroids": centroids}


@pytest.fixture
def two_touching_circles():
    """Two overlapping/touching white disks on black — a plain connected-
    components label sees ONE region; watershed (using the distance
    transform) should split it into two.
    """
    from skimage.draw import disk

    arr = _np.zeros((80, 140), dtype=_np.uint8)
    rr, cc = disk((40, 45), 30, shape=arr.shape)
    arr[rr, cc] = 255
    rr, cc = disk((40, 95), 30, shape=arr.shape)
    arr[rr, cc] = 255
    return arr


@pytest.fixture
def one_disk_blob():
    """A single solid disk of known center/radius on black — an
    independent-of-detector-code oracle for DetectBlobs (drawn via
    skimage.draw, detected via skimage.feature.blob_log/blob_dog — different
    code paths)."""
    from skimage.draw import disk

    arr = _np.zeros((100, 100), dtype=_np.uint8)
    rr, cc = disk((50, 50), 12, shape=arr.shape)
    arr[rr, cc] = 255
    return {"arr": arr, "center": (50.0, 50.0), "radius": 12.0}


@pytest.fixture
def vertical_step_edge():
    """A hard black|white vertical step at column 40 — the edge oracle: all
    "true" edges lie on that one column."""
    arr = _np.zeros((60, 80), dtype=_np.uint8)
    arr[:, 40:] = 255
    return arr


@pytest.fixture
def white_square_corners():
    """A white square on black with four corners at exactly known pixel
    coordinates — the corner-detection oracle."""
    arr = _np.zeros((100, 100), dtype=_np.uint8)
    arr[20:80, 20:80] = 255
    corners = [(20, 20), (20, 79), (79, 20), (79, 79)]
    return {"arr": arr, "corners": corners}


@pytest.fixture
def uniform_gray():
    """A perfectly uniform mid-gray image — the textbook GLCM/statistics/
    entropy oracle: contrast=0, homogeneity=1, energy=1, entropy=0, std=0."""
    return _np.full((64, 64), 100, dtype=_np.uint8)


@pytest.fixture
def solid_red():
    """A uniform solid-red RGB image — the color-conversion oracle (the
    standard ITU-R 601-2 luma formula gives an exact expected gray value)."""
    return _np.zeros((40, 40, 3), dtype=_np.uint8) + _np.array([255, 0, 0], dtype=_np.uint8)


@pytest.fixture
def noisy_gradient():
    """A smooth diagonal gradient with additive Gaussian noise — the
    denoise oracle: std(denoised) must be lower than std(noisy) since the
    ground-truth signal is smooth."""
    rng = _np.random.default_rng(42)
    ramp = _np.linspace(0, 255, 96, dtype=_np.float64)
    base = _np.tile(ramp, (96, 1))
    noisy = base + rng.normal(0, 25, size=base.shape)
    return _np.clip(noisy, 0, 255).astype(_np.uint8)
